const STATUS_CODE_SUCESS = {
    OK: 200,
    CREATED: 201
}


const STATUS_CODE_CLIENT = {
	BAD_REQUEST: 400,
    NOT_AUTH: 401,
    NOT_FOUND: 404
}

const STATUS_CODE_SERVER ={
	INTERNAL_SERVER_ERROR: 500,
}

export default {STATUS_CODE_SUCESS, STATUS_CODE_CLIENT, STATUS_CODE_SERVER}